apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-spam2000
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  groups:
    - name: spam2000.rules
      rules:
        - alert: Spam2000Down
          expr: up{job="spam2000"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Spam2000 application is down"
            description: "Spam2000 application has been down for more than 1 minute"
        
        - alert: Spam2000HighMemory
          expr: process_resident_memory_bytes{job="spam2000"} > 200000000
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Spam2000 high memory usage"
            description: "Spam2000 is using more than 200MB of memory"
