# Victoria Metrics values with custom configuration
victoria-metrics-single:
  # Service configuration
  service:
    type: ClusterIP
    port: 8428

  # Security context - best practice
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  # Pod security context
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  # Resource requirements - optimized
  server:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi

  # Persistence configuration
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: ""
    accessModes:
      - ReadWriteOnce

  # Retention settings
  retentionPeriod: 30d

  # Labels for better organization
  podLabels:
    app.kubernetes.io/name: victoria-metrics
    app.kubernetes.io/component: tsdb
    app.kubernetes.io/part-of: monitoring

  # Disable any complex features
  serviceMonitor:
    enabled: false

  # Basic container settings
  containerPort: 8428

  # Victoria Metrics configuration
  extraArgs:
    - --httpListenAddr=:8428
    - --maxHourlySeries=1000000
    - --maxDailySeries=1000000
    - --retentionPeriod=30d
    - --storageDataPath=/storage
    - --search.maxUniqueTimeseries=1000000
    - --search.maxSamplesPerQuery=1000000
    - --search.maxQueueDuration=30s
    - --search.maxConcurrentRequests=10
    - --search.logSlowQueryThreshold=5s
    - --logLevel=INFO
    - --enableTCP6=false
    - --maxConcurrentInserts=4
    - --insertAuthKey=
    - --search.maxUniqueTimeseries=1000000
    - --search.maxSamplesPerQuery=1000000
    - --search.maxQueueDuration=30s
    - --search.maxConcurrentRequests=10
    - --search.logSlowQueryThreshold=5s

  # Metrics collection configuration
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
    prometheusRule:
      enabled: false

  # Health check configuration
  livenessProbe:
    httpGet:
      path: /health
      port: 8428
    initialDelaySeconds: 30
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /health
      port: 8428
    initialDelaySeconds: 5
    periodSeconds: 5

  # Service account
  serviceAccount:
    create: true
    name: victoria-metrics-single

  # Scrape configuration for metrics collection
  scrapeConfigs:
    - job_name: 'victoria-metrics-self'
      static_configs:
        - targets: ['localhost:8428']
      metrics_path: '/metrics'
      scrape_interval: 15s
      scrape_timeout: 10s
      honor_labels: true

  # Optimized scrape configurations
  extraScrapeConfigs:
    - job_name: 'spam2000-app'
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - spam2000
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: '([^:]+)(?::\d+)?;(\d+)'
          replacement: '${1}:${2}'
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
      scrape_interval: 30s
      scrape_timeout: 10s
