# Victoria Metrics values with custom configuration
victoria-metrics-single:
  # Basic service configuration
  service:
    type: ClusterIP
    port: 8428
  
  # Resource requirements - use correct Helm chart structure
  server:
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 512Mi
  
  # Persistence configuration
  persistence:
    enabled: true
    size: 5Gi
  
  # Basic settings
  retentionPeriod: 30d
  
  # Disable problematic features
  podDisruptionBudget:
    enabled: false
  
  # Security context
  securityContext:
    runAsNonRoot: false
    runAsUser: 1000
  
  # Pod labels that match our network policy
  podLabels:
    app.kubernetes.io/name: victoria-metrics-single
    app.kubernetes.io/part-of: monitoring
  
  # Service labels
  serviceLabels:
    app.kubernetes.io/name: victoria-metrics-single
    app.kubernetes.io/part-of: monitoring
  
  # Disable any complex features
  serviceMonitor:
    enabled: false
  
  # Basic container settings
  containerPort: 8428
  
  # Victoria Metrics configuration
  extraArgs:
    - --httpListenAddr=:8428
    - --maxHourlySeries=1000000
    - --maxDailySeries=1000000
    - --retentionPeriod=30d
    - --storageDataPath=/storage
    - --search.maxUniqueTimeseries=1000000
    - --search.maxSamplesPerQuery=1000000
    - --search.maxQueueDuration=30s
    - --search.maxConcurrentRequests=10
    - --search.logSlowQueryThreshold=5s
    - --logLevel=INFO
    - --enableTCP6=false
    - --maxConcurrentInserts=4
    - --insertAuthKey=
    - --search.maxUniqueTimeseries=1000000
    - --search.maxSamplesPerQuery=1000000
    - --search.maxQueueDuration=30s
    - --search.maxConcurrentRequests=10
    - --search.logSlowQueryThreshold=5s
  
  # Metrics collection configuration
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
    prometheusRule:
      enabled: false
  
  # Health check configuration
  livenessProbe:
    httpGet:
      path: /health
      port: 8428
    initialDelaySeconds: 30
    periodSeconds: 10
  
  readinessProbe:
    httpGet:
      path: /health
      port: 8428
    initialDelaySeconds: 5
    periodSeconds: 5
  
  # Service account
  serviceAccount:
    create: true
    name: victoria-metrics-single
  
  # Pod security context
  podSecurityContext:
    fsGroup: 1000
    runAsNonRoot: false
    runAsUser: 1000
  
  # Scrape configuration for metrics collection
  scrapeConfigs:
    - job_name: 'victoria-metrics-self'
      static_configs:
        - targets: ['localhost:8428']
      metrics_path: '/metrics'
      scrape_interval: 15s
      scrape_timeout: 10s
      honor_labels: true
  
  # Additional scrape configs for external targets
  extraScrapeConfigs:
    - job_name: 'spam2000-app'
      static_configs:
        - targets: ['spam2000.spam2000.svc.cluster.local:3000']
      metrics_path: '/metrics'
      scrape_interval: 15s
      scrape_timeout: 10s
      honor_labels: true
      relabel_configs:
        - source_labels: [__address__]
          target_label: instance
          regex: '([^:]+)(?::\d+)?'
          replacement: '${1}'
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_service_name]
          target_label: service
    
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: '([^:]+)(?::\d+)?;(\d+)'
          replacement: '${1}:${2}'
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
