# Victoria Metrics values with custom configuration
victoria-metrics-single:
  # Service configuration
  service:
    type: ClusterIP
    port: 8428

  # Security context - best practice
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  # Pod security context
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  # Resource requirements - optimized
  server:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi

  # Persistence configuration
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: ""
    accessModes:
      - ReadWriteOnce

  # Retention settings
  retentionPeriod: 30d

  # Labels for better organization
  podLabels:
    app.kubernetes.io/name: victoria-metrics
    app.kubernetes.io/component: tsdb
    app.kubernetes.io/part-of: monitoring

  # Disable any complex features
  serviceMonitor:
    enabled: false

  # Basic container settings
  containerPort: 8428

  # Victoria Metrics server configuration
  server:
    # Add scrape config argument
    extraArgs:
      - --promscrape.config=/etc/victoria-metrics/scrape-config.yaml
    # Mount the scrape config
    extraVolumeMounts:
      - name: scrape-config
        mountPath: /etc/victoria-metrics
        readOnly: true
    # Add the scrape config volume
    extraVolumes:
      - name: scrape-config
        configMap:
          name: victoria-metrics-scrape-config

  # Metrics collection configuration
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
    prometheusRule:
      enabled: false

  # Health check configuration
  livenessProbe:
    httpGet:
      path: /health
      port: 8428
    initialDelaySeconds: 30
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /health
      port: 8428
    initialDelaySeconds: 5
    periodSeconds: 5

  # Service account
  serviceAccount:
    create: true
    name: victoria-metrics-single
