replicaCount: 1

image:
  repository: andriiuni/spam2000
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
