apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "victoria-metrics.fullname" . }}-scrape-config
  labels:
    {{- include "victoria-metrics.labels" . | nindent 4 }}
data:
  scrape-config.yaml: |
    global:
      scrape_interval: 30s
      scrape_timeout: 10s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'victoria-metrics-self'
        static_configs:
          - targets: ['localhost:8428']
        metrics_path: '/metrics'
        scrape_interval: 15s
        scrape_timeout: 10s
        honor_labels: true

      - job_name: 'spam2000-app'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - spam2000
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: '([^:]+)(?::\d+)?;(\d+)'
            replacement: '${1}:${2}'
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
