apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vmagent-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  scrape-config.yaml: |
    global:
      scrape_interval: 30s
      scrape_timeout: 10s
    
    scrape_configs:
      - job_name: 'victoria-metrics-self'
        static_configs:
          - targets: ['localhost:8428']
        metrics_path: '/metrics'
        scrape_interval: 15s
        scrape_timeout: 10s
        honor_labels: true

      - job_name: 'spam2000-app'
        static_configs:
          - targets: ['spam2000.spam2000.svc.cluster.local:3000']
        metrics_path: /metrics
        scrape_interval: 30s
        scrape_timeout: 10s
