apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: spam2000-network-policy
  namespace: spam2000
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: spam2000
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 3000
  - from:
    - namespaceSelector:
        matchLabels:
          name: argocd
    ports:
    - protocol: TCP
      port: 3000
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to: []