apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spam2000.fullname" . }}
  labels:
    {{- include "spam2000.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "spam2000.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spam2000.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository | default "andriiuni/spam2000" }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.service.targetPort | default 8080 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
