apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 6.60.6
    chart: grafana
    helm:
      values: |
        adminPassword: admin
        persistence:
          enabled: true
          size: 10Gi
        
        # Grafana service configuration - use 3001 for both external and internal
        service:
          type: ClusterIP
          port: 3001
          targetPort: 3001
        
        # Grafana server configuration - listen on port 3001 internally
        grafana.ini:
          server:
            http_port: 3001
        
        # Health check probes - use port 3001
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        
        ingress:
          enabled: false
        
        # Resource limits and requests to satisfy namespace quota
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 512Mi
        
        # Init container resources
        initChownData:
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
        
        # Sidecar resources
        sidecar:
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
