apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 6.60.6
    chart: grafana
    helm:
      values: |
        adminPassword: admin
        persistence:
          enabled: true
          size: 10Gi
        service:
          type: ClusterIP
        ingress:
          enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
