apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://victoriametrics.github.io/helm-charts'
    targetRevision: 0.9.0
    chart: victoria-metrics-single
    helm:
      values: |
        service:
          type: ClusterIP
        persistence:
          enabled: true
          size: 10Gi
        retentionPeriod: 30d
        
        # Resource limits and requests to satisfy namespace quota
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 1Gi
        
        # Pod disruption budget
        podDisruptionBudget:
          enabled: true
          minAvailable: 1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
