apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://victoriametrics.github.io/helm-charts'
    targetRevision: 0.9.0
    chart: victoria-metrics-single
    helm:
      values: |
        # Basic service configuration
        service:
          type: ClusterIP
          port: 8428
        
        # Resource requirements - use correct Helm chart structure
        server:
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 512Mi
        
        # Persistence configuration
        persistence:
          enabled: true
          size: 5Gi
        
        # Basic settings
        retentionPeriod: 30d
        
        # Disable problematic features
        podDisruptionBudget:
          enabled: false
        
        # Security context
        securityContext:
          runAsNonRoot: false
          runAsUser: 1000
        
        # Pod labels that match our network policy
        podLabels:
          app.kubernetes.io/name: victoria-metrics-single
          app.kubernetes.io/part-of: monitoring
        
        # Service labels
        serviceLabels:
          app.kubernetes.io/name: victoria-metrics-single
          app.kubernetes.io/part-of: monitoring
        
        # Disable any complex features
        serviceMonitor:
          enabled: false
        
        # Basic container settings
        containerPort: 8428
        extraArgs:
          - --httpListenAddr=:8428
          - --maxHourlySeries=1000000
          - --maxDailySeries=1000000
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
