apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<your-username>/spam2000-gitops.git'
    targetRevision: main
    chart: victoria-metrics-single
    helm:
      values: |
        {{- .Files.Get "monitoring/victoria-metrics/values.yaml" | nindent 8 }}
    repoURL: 'https://victoriametrics.github.io/helm-charts'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
